### ISSUE TITLE
Recommended exiftool settings

### ISSUE THREAD

**Issue by ptr727** [fuxs/teekesselchen#5]
Hi, this is not really an issue, more a suggestion for default settings.

After lots of experimentation using exiftool 10.03 and my 84K big library, I found the following exiftool flags worked well: 
-SequenceNumber -SubSecTime -SpecialMode -MetaDataDate -FileNumber -SubSecDateTimeOriginal -ThumbnailLength -ImageNumber

Using the default set of options produced many false positives, due to the size of my library I could not verify false negatives.

For the following file types in my library these options produced unique results:

Canon JPG:
MetaDataDate

CR2:
FileNumber

NEF:
FileNumber

iPhone 4:
CustomRendered
ThumbnailLength

iPhone 5S:
ThumbnailLength
SubSecDateTimeOriginal

D90 JPG:
ImageNumber

**Comment by ptr727** [comment]
See https://github.com/fuxs/teekesselchen/pull/4

**Comment by Juuro** [comment]
I still get false positive duplicates with those settings for photos (Canon CR2, Canon 6D) taken in the same second. :-(

**Comment by ptr727** [comment]
Closing since the recommended parameters were already added.
